### ISSUE TITLE
How to set multiple type of barcode ?

### ISSUE THREAD

**Issue by pujislamet** [julienboulay/ngx-barcode-scanner#1]
I want barcode-live-streaming set to detect multiple type of barcode.
How to set multiple type in "type" atributte ? I tried with coma (,) separator, but it doesnt work.

**Comment by beyondtheobservableuniverse** [comment]
Any solution for this issue?

**Comment by lucifer63** [comment]
You have no access to quagga config via BarecodeScannerLivestreamComponent, so if you wanna set some attributes or change type processing you have to commit a PR with corresponding changes or fork this project.

**Comment by jnjaga24** [comment]
any update on this issue?

**Comment by lucifer63** [comment]
@jnjaga24, no, as you can see from the commit list. Anyway, look at the ```type``` property of the overlay component, it has no additional logic to operate multiple types. Just change type of its value to array and make corresponding changes to https://github.com/julienboulay/ngx-barcode-scanner/blob/master/projects/ngx-barcode-scanner/src/lib/barcode-scanner-livestream/barcode-types.ts file.

Message me if you have troubles with it

**Comment by Sampath-Lokuge** [comment]
```
<barcode-scanner-livestream [type]="['ean','upc']" (valueChanges)="onValueChanges($event)">
</barcode-scanner-livestream>
```
