### ISSUE TITLE
Camera focus control

### ISSUE THREAD

**Issue by mer30boy** [julienboulay/ngx-barcode-scanner#100]
Hi.
In some devices, the automatic focus does not work well and barcode scanning is difficult.
Is there a way to manage the focus operation of the camera?
For example, by calling a function, the camera will focus on the center of the image.
Is it possible to add this feature?

**Comment by julienboulay** [comment]
Hi @mer30boy ,

Thank you for using `ngx-barcode-scanner`
It seems that some devices have multiple camera with various resolution.
In your case, the wrong camera might be selected by default.
Please have a look to [this post on quaggajs github](https://github.com/serratus/quaggaJS/issues/380#issuecomment-566130150) and let me know if it solves your issue

**Comment by mer30boy** [comment]
thank you for your attention
I had already read this post. Also, in my app, I give this feature to the user to select the camera.
The application that I am developing must work in a low-light environment, and in this type of environment, the automatic focus does not work well on some devices. As a result, a tool to manage camera focus can be very helpful.

**Comment by julienboulay** [comment]
@mer30boy ,
If your app need to work in a low-light environnement, did you try to light the torch ?

Also, did you try the `locate: false` option, as described in [this post](https://github.com/serratus/quaggaJS/issues/365#issuecomment-483446435)

**Comment by mer30boy** [comment]
@julienboulay
Yes . The first thing I did was to add a torch control. Although it was effective, it did not solve the autofocus problem.

I also tested the `locate: false`, but I didn't get any results, although I didn't understand what exactly it does.

However, is it possible to add focus control or not?

**Comment by julienboulay** [comment]
@mer30boy

I've tried the following :

```
            const track = Quagga.CameraAccess.getActiveTrack();
            console.log(track.getCapabilities());
            track.applyConstraints({
                advanced: [{
                    focusMode: 'continuous'
                }]
            });
```

But `focusMode` is not a recognized constraint, and doesn't seem to be a setting that can be modified.

Have you tried `track.getCapabilities()` to check your device capabilities ?
Maybe try to select the device that has `focusMode='continuous'` ?

**Comment by mer30boy** [comment]
@julienboulay

> Have you tried track.getCapabilities() to check your device capabilities ?

no really
To access the track object, we need the Quagga object. Is it possible to access the Quagga object through the `<barcode-scanner-livestream>` ?

**Comment by julienboulay** [comment]
@mer30boy 

Yes, you should be able to access it when the component is ready

In your template :
```
<barcode-scanner-livestream
    (started)="onStarted($event)"
  ></barcode-scanner-livestream>
```

In your component : 
```
import Quagga from '@ericblade/quagga2';

export class BarcodeReader {

...

    onStarted(event): void {
        const track = Quagga.CameraAccess.getActiveTrack();
        console.log(track.getCapabilities());
    }
}
```

**Comment by mer30boy** [comment]
> 

I ran the  track.getCapabilities() on different devices.
The result of focusMode in different cameras is as follows:

Selfie Camera:
![front](https://user-images.githubusercontent.com/52951244/215548125-93242f83-fa0c-4060-97e2-6b4b8838331d.jpg)

Back Camera :
![back](https://user-images.githubusercontent.com/52951244/215548170-b404b325-84ce-4019-b1e5-17e906bb4d13.jpg)

**Comment by julienboulay** [comment]
@mer30boy 

And if you run `track.getContraints()` or `track.getSettings()` ?

**Comment by mer30boy** [comment]
> @mer30boy
> 
> And if you run `track.getContraints()` or `track.getSettings()` ?

`track.getContraints()` : 
![cons](https://user-images.githubusercontent.com/52951244/215739843-1e3b9cd6-7834-4b22-b16d-8b1f56caaa81.jpg)

`track.getSettings()` : 
![setting](https://user-images.githubusercontent.com/52951244/215739898-68685084-e4d3-489a-9b79-7167ef9feaf9.jpg)

**Comment by julienboulay** [comment]
@mer30boy it seems that your device already use `continuous` autofocus.

Have you tried to modify width/height/aspectRatio in the component config, to get better resolution ?

Here are the default settings in ngx-barcode-scanner :
```
inputStream: {
      constraints: {
          width: { min: 640 },
          height: { min: 480 },
          aspectRatio: { min: 1, max: 2 }
      }
}
```

Your device seems to support 3000x4000 resolution

**Comment by mer30boy** [comment]
Yes . I already tried increasing the resolution and things like that.
But as I mentioned, the main problem is the lack of light, which causes problems in the automatic focus of the camera.
In the phone camera app, when we click on a part of the image received from the camera, the camera focuses on that part.
Is it possible to implement this feature in ngx-barcode-scanner?

**Comment by julienboulay** [comment]
@mer30boy No, I'm sorry. I didn't find any solution for that.
