### ISSUE TITLE
facing compilation issue when include bar scanner component

### ISSUE THREAD

**Issue by sivaramalingam** [julienboulay/ngx-barcode-scanner#104]
I'm using Angular 12 application, and installed necessary libraires for ngx-barcode-scanner(^0.3.0) and @ericblade/quagga2(1.8.2). The compilation is working in the console only, but in the browser I got the JIT compilation issue, PFA image. 

I have tried the following approaches: 
1. update the package.json like below. 
"postinstall": "ngcc --properties es5 browser module main --first-only --create-ivy-entry-points"
2. remove the node modules folder and package-lock.json file. 
3. run the application using --aot=true as well. 

<img width="886" alt="image" src="https://github.com/julienboulay/ngx-barcode-scanner/assets/7724622/231347fe-e18f-42ba-91b6-bc61f2164e7f">

**Comment by julienboulay** [comment]
Hi @sivaramalingam,

I've never seen this issue with angular12.
Did you successfully build your project without `ngx-barecode-scanner` ?
Could you please provide a repository to be able to reproduce this issue ?
