### ISSUE TITLE
@ericblade/quagga2 can cause optimization bailouts.

### ISSUE THREAD

**Issue by Neizan93** [julienboulay/ngx-barcode-scanner#105]
node_modules\.pnpm\ngx-barcode-scanner@0.2.0_@angular+common@15.2.10_@angular+core@15.2.10_@ericblade+quagga2@1.8.2\node_modules\ngx-barcode-scanner\__ivy_ngcc__\fesm2015\ngx-barcode-scanner.js depends on '@ericblade/quagga2'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by julienboulay** [comment]
Hi Neizan93,

@ericblade/quagga2 is a commonjs peer dependency and is not maintained through `ngx-barcode-scanner` project.
An issue related to ESM and Angular is already opened on quagga2 repo :
https://github.com/ericblade/quagga2/issues/485
