### ISSUE TITLE
What are the other type supported?

### ISSUE THREAD

**Issue by blackxrabbit** [julienboulay/ngx-barcode-scanner#2]
I tried to use other format but it seems not working..Are other fornat supported?

**Comment by beyondtheobservableuniverse** [comment]
Any solution for this issue?

**Comment by lucifer63** [comment]
> I tried to use other format but it seems not working..Are other fornat supported?

What format have you tried, are we talking about _type_ attribute?

**Comment by julienboulay** [comment]
@blackxrabbit I'm back on the library after a long unavailability period.

Here is the list of available types :
`code_128`
 `code_39`
`code_39_vin`
`ean`
`ean_extended`
`ean_8`
`upc`
 `upc_e`
`codabar`
`i2of5`
`2of5`
`code_93`

**Comment by Sampath-Lokuge** [comment]
How to give an array of type?
