### ISSUE TITLE
Not able to scan barcode for A:ASN-12:19-000064

### ISSUE THREAD

**Issue by tilakdewangan-gep** [julienboulay/ngx-barcode-scanner#20]
Hi Team,

You guys are doing a great job and I appreciate your work.

I just wanted to inform the team that when I am scanning the barcode created for A:ASN-12:19-000064 then scanner is not able to read and sometimes it does but it returns garbage value.

I tried to scan from the website on the following devices - 
OnePlus7
Dell laptop
Microsoft Surface

It would be a great help if the team get a chance to fix this issue?

Thank you

**Comment by julienboulay** [comment]
Hi,
ngx-barcode-scanner is just a wrapper of quaggajs. 
Before opening an issue,  please verify that you can read your barcode with livestream example https://serratus.github.io/quaggaJS/examples/live_w_locator.html
Select the type of barcode and try to read it with your webcam
