### ISSUE TITLE
EAN 13 Support

### ISSUE THREAD

**Issue by unitrix0** [julienboulay/ngx-barcode-scanner#21]
Actually not a issue but a question: Does is support EAN13? I've tried all the EAN types but it detects only rubbish... 

thanks

**Comment by julienboulay** [comment]
Hi @unitrix0 ,
Yes, EAN13 should be supported by quaggajs.
See https://serratus.github.io/quaggaJS/#configobject
Try to use `type="ean"` on the component and it should work
