### ISSUE TITLE
Build failed with Error: Can't resolve 'quagga'

### ISSUE THREAD

**Issue by nrogers805** [julienboulay/ngx-barcode-scanner#22]
ERROR in ./node_modules/ngx-barcode-scanner/fesm5/ngx-barcode-scanner.js
Module not found: Error: Can't resolve 'quagga' in 'C:\Users\Norm\Dropbox\Norm\Documents\Visual Studio Code\AMZSC_FrontEnd\node_modules\ngx-barcode-scanner\fesm5'

I installed quagga but got same error

**Comment by julienboulay** [comment]
Hi @nrogers805,

Strange error. It should work with QuaggaJS installed in your node_modules. 
Did you solve this issue ?
Otherwise, could you paste your package.json or provide a github repository with a failing example ?
