### ISSUE TITLE
Not reading barcodes

### ISSUE THREAD

**Issue by devpato** [julienboulay/ngx-barcode-scanner#23]
I have scanned 3 different barcodes from things i have in my kitchen, and it doesnt read any of them. Am I missing something? It adds the green square detecting the qr but nothing gets printed on the html nor the console

```
 onValueChanges(result){
        console.log(result);
        this.barcodeValue = result.codeResult.code;
    }
```

```
<barcode-scanner-livestream type="code_128" (valueChanges)="onValueChanges($event)" (started)="onStarted"></barcode-scanner-livestream>
    <div [hidden]="!barcodeValue">
        {{barcodeValue}}
    </div>
```

**Comment by julienboulay** [comment]
hi @devpato ,

Maybe try to use different barecode type(s) ?
Do you know the type of the barcode you try to read ?
