### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by Fernyan** [julienboulay/ngx-barcode-scanner#25]
Can someone post a Demo? I tried follow the steps in "Usage" but nothing happened

**Comment by Fernyan** [comment]
What I use to scan? Image? WebCam? Document?

**Comment by julienboulay** [comment]
> Can someone post a Demo? I tried follow the steps in "Usage" but nothing happened

I'm sorry, I don't really have the time to post a demo.

**Comment by julienboulay** [comment]
> What I use to scan? Image? WebCam? Document?
This library implement only live recognition (with a Webcam), but quaggajs allow to use Image recognition

**Comment by Fernyan** [comment]
Following the readme.md has a complete angular demo, so I made this one: [https://github.com/Fernyan/DemoNgxBarcode](url)

**Comment by julienboulay** [comment]
@Fernyan I can't see any line of code referring to ngx-barcode-scanner on your project.
Do you forgot to push the code on github ?

**Comment by Fernyan** [comment]
I forgot to update the repository 😄
