### ISSUE TITLE
barcode scanner as keyboard

### ISSUE THREAD

**Issue by slatribat** [julienboulay/ngx-barcode-scanner#26]
Hi.
My barcodescanner emulates a keyboard - i tried the code under "Usage" but the event did not trigger - is there a separate type to use with regular keyboard input? Or is perhaps easier in this case to just use @HostListener ?

**Comment by julienboulay** [comment]
Hi @slatribat ,
I'm sorry, I don't really understand the issue.
Could you please give some code sample or a project to reproduce the error ?
What do you mean by
> My barcodescanner emulates a keyboard

?

**Comment by slatribat** [comment]
Hi.
The input comes as a stream of characters. But the event was never fired with ngx-barcode-scanner. I got i working anyway by configuring the scanner to send 2ms delay between each token...
