### ISSUE TITLE
How to configure space taken by camera on screen?

### ISSUE THREAD

**Issue by waqqas-meraj-rt** [julienboulay/ngx-barcode-scanner#28]
How can I configure space taken by camera on screen? Currently, it occupies pretty much the whole screen. How can I allocate a, say 400 x 400 pixel area for bar code live stream output? Thanks.

**Comment by julienboulay** [comment]
Hi @waqqas-meraj-rt ,

Thank you for using ngx-barcode-scanner.
You can fix the size of the livestream output just by css:

```
.barcode-scanner-livestream-overlay-content {
   width: 400px;
   height: 400px;
}
```
