### ISSUE TITLE
How to set deviceId for quagga configuration?

### ISSUE THREAD

**Issue by jorgecuevas92** [julienboulay/ngx-barcode-scanner#3]
I'm trying to set the camera input by configuring the deviceId, so I can get the front camera on a tablet:

I took a look on the config sent to quagga which is shown below:

```
var DEFAULT_CONFIG = {
    inputStream: {
        name: 'Live',
        type: 'LiveStream',
        target: null,
        constraints: {
            width: { min: 640 },
            height: { min: 480 },
            aspectRatio: { min: 1, max: 100 },
            facingMode: 'environment',
        },
        singleChannel: false
    },
    locator: {
        patchSize: 'medium',
        halfSample: true
    },
    locate: true,
    numOfWorkers: 4,
    decoder: {
        readers: ['code_128_reader']
    }
};
```

What is the correct way to set the deviceId property?

**Comment by lucifer63** [comment]
Read [Input stream](https://github.com/serratus/quaggaJS#inputstream) section at QuaggaJS main page.

**Comment by ericblade** [comment]
Scanning the internet for incorrect uses of aspectRatio: max: 100 .  Please use max: 2 or something closer to that, as 100 breaks the visuals in iOS 14+
