### ISSUE TITLE
Formats Supported

### ISSUE THREAD

**Issue by arunpanchavadi** [julienboulay/ngx-barcode-scanner#32]
Which are the barcode formats supported by ngx-barcode-scanner?

**Comment by MaddMugsy** [comment]
I found a list here:

https://github.com/julienboulay/ngx-barcode-scanner/blob/master/projects/ngx-barcode-scanner/src/lib/barcode-scanner-livestream/barcode-types.ts

What I'd like to know is how to specify multiple types for scanning.  It looks like there's support for scanning multiple types at once, but there's no obvious syntax for doing so.
