### ISSUE TITLE
ERROR TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by ricocynthia** [julienboulay/ngx-barcode-scanner#34]
When I build my app with `BarecodeScannerLivestreamComponent` implemented i get the following error: 
`ERROR TypeError: Cannot read property 'start' of undefined`. 

This is what I have in my `search.component.ts` file where I am trying to use `BarecodeScannerLivestreamComponent`:
```
  @ViewChild(BarecodeScannerLivestreamComponent)
  barecodeScanner: BarecodeScannerLivestreamComponent;
  barcodeValue;

 ngAfterViewInit() {
    console.log(this.barecodeScanner);
    this.barecodeScanner.start();
  }

  onValueChanges(result) {
    this.barcodeValue = result.codeResult.code;
  }
```

I also made sure to add `BarecodeScannerLivestreamModule` in my module.

This error is happening because `this.barecodeScanner` is undefined. Does anyone know how to overcome this?

**Comment by ehdwns980416** [comment]
Do you add `<barcode-scanner-livestream></barcode-scanner-livestream>` this tag in your `search.component.html` of template?
