### ISSUE TITLE
hi can you helpme plz

### ISSUE THREAD

**Issue by gsusferrer** [julienboulay/ngx-barcode-scanner#38]
3 things: 

1. Exist one way to add various types in tag barcode-scanner-livestream ?
2. Its work with a real barcode scanner? only works in my app from the camera no from usb scanner.
3. I have this problem when te app enter in my barcodeReader component: 

![error](https://user-images.githubusercontent.com/25061972/90597499-41f80d80-e1bf-11ea-875f-f0a85d64f0dd.png)

thanks 4 your great apport.

**Comment by julienboulay** [comment]
Hi @gsusferrer ,

1. You will find the list of supported types [here](https://github.com/julienboulay/ngx-barcode-scanner/blob/master/projects/ngx-barcode-scanner/src/lib/barcode-scanner-livestream/barcode-types.ts)
2. It is not intended to work with barcode scanner device. QuaggaJS is only compatible with webcam and camera
3. It seems that your camera could not be found
