### ISSUE TITLE
Compile error in "0.0.10"?

### ISSUE THREAD

**Issue by mnesser** [julienboulay/ngx-barcode-scanner#44]
After update to latest version ("0.0.10") I get compile error: 

`ERROR in The target entry-point "ngx-barcode-scanner" has missing dependencies:
 - lodash.defaultsdeep`

**Comment by julienboulay** [comment]
Hi @mnesser ,

Yes, I'm sorry. I missed this dependency in the last package. Can you try `npm i --save 'lodash.defaultsdeep'` ?

**Comment by julienboulay** [comment]
Fixed in v0.0.11
