### ISSUE TITLE
How to change the frequency of scans?

### ISSUE THREAD

**Issue by Naruto248** [julienboulay/ngx-barcode-scanner#45]
In QuaggaJS there is an option to change the frequency of scans, but I'm not able to set the frequency in the config property from my component.ts (Even if I set the frequency in config, it doesn't work).

**Comment by julienboulay** [comment]
Hi @Naruto248,

I cannot reproduce this bug. If I define a config property `config = { frequency: 1 }` and pass it to the component `[config]="config"` the frequency is set to 1 scan per second.
Could you provide a repo where I can reproduce this bug
