### ISSUE TITLE
Cannot close barcodescanner

### ISSUE THREAD

**Issue by soucik** [julienboulay/ngx-barcode-scanner#46]
When this.barecodeScanner.hide(); is called, nothing happens.

In barcode-scanner-livestream.component.js (node_modules) line 54, stop function should look like this:
    stop() {
        if (this._started) {
            this.stop();
            Quagga.stop();
            this._started = false;
            this.started.next(false);
        }
    }

this.stop(); should fix issue.

**Comment by Sampath-Lokuge** [comment]
Can you tell me how to stop after finding 1 Barcode?

**Comment by julienboulay** [comment]
@soucik, 
I don't understand what is your issue and why you call `stop` function recursively.

As @Sampath-Lokuge write, the barcode scanner can be stopped after reading the code result

**Comment by Sampath-Lokuge** [comment]
@julienboulay Yes, this is a great module for the Barcode scaning. Thanks a lot!

**Comment by julienboulay** [comment]
@Sampath-Lokuge many thanks
