### ISSUE TITLE
Wrong spelling and not followed the naming convention

### ISSUE THREAD

**Issue by Sampath-Lokuge** [julienboulay/ngx-barcode-scanner#47]
Hi,

We hope you'll fix those in the future version.

**Wrong Spelling**

`BarecodeScannerLivestreamModule`

**Correct Spelling**

`BarcodeScannerLivestreamModule`

**Not followed the naming convention**

`BarecodeScannerLivestreamModule`

**Correct naming convention**

`BarcodeScannerLiveStreamModule`

I use this VS Code extension to avoid those: https://github.com/streetsidesoftware/vscode-spell-checker

**Comment by julienboulay** [comment]
Hi @Sampath-Lokuge,

It will be fixed in next 0.12 release

**Comment by Sampath-Lokuge** [comment]
Hi @julienboulay 
Ok sure. Great! Thanks!
