### ISSUE TITLE
Not working on iOS Chrome

### ISSUE THREAD

**Issue by Sampath-Lokuge** [julienboulay/ngx-barcode-scanner#49]
Hi,

This is working fine on iOS Safari. But it gives the below error on iOS Chrome. Any help here?

>LOGError: getUserMedia is not defined
ERRORError: Uncaught (in promise): Error: getUserMedia is not defined
a@https://my-be385.web.app/5.c963b72d402ba79cb199.js:1:140957
o@https://my-be385.web.app/5.c963b72d402ba79cb199.js:1:146771
o@[native code]
onInvoke@https://my-be385.web.app/main.a0ca28d2e5a97379764b.js:1:330125
run@https://my-be385.web.app/polyfills.8a7ad34546da8efa99a1.js:1:2042
https://my-be385.web.app/polyfills.8a7ad34546da8efa99a1.js:1:12977
onInvokeTask@https://my-be385.web.app/main.a0ca28d2e5a97379764b.js:1:330018
runTask@https://my-be385.web.app/polyfills.8a7ad34546da8efa99a1.js:1:2661
m@https://my-be385.web.app/polyfills.8a7ad34546da8efa99a1.js:1:9243
invokeTask@https://my-be385.web.app/polyfills.8a7ad34546da8efa99a1.js:1:8322
_@https://my-be385.web.app/polyfills.8a7ad34546da8efa99a1.js:1:20553
k@https://my-be385.web.app/polyfills.8a7ad34546da8efa99a1.js:1:20793

**Comment by julienboulay** [comment]
Hi,

As detailed in README file, access to getUserMedia is restricted on iOS.

> Access to the camera is restricted on iOS when running in a Progressive Web App

Also, it is not supported on Chrome browser

See https://developer.apple.com/forums/thread/650785

**Comment by Sampath-Lokuge** [comment]
Ok sure. Thanks for the info.
