### ISSUE TITLE
Can't build the component

### ISSUE THREAD

**Issue by lucifer63** [julienboulay/ngx-barcode-scanner#5]
Hello!

I need to change 2 little things in your component:
1. In `start` procedure return the promise that `_init` returns, i need this in order to manually catch errors that can occur during initialization,
2. In `onDetected` return the whole `result` object instead of `result.codeResult.code`, i need it in order to be able to analyze errors in `result.codeResult.decodedCodes` as described [here](https://github.com/serratus/quaggaJS/issues/237).

I cloned the project, executed `npm i` and the troubles started to occure right there. I think there's no need to list all the errors that occured, there were hella lot of them - with npm, with angular, with typescript, with everything; i struggled for hours to make it work but no luck.

Can you please help me with it?

Thanks in advance!

**Comment by julienboulay** [comment]
Hi @lucifer63,

Thank you for your feedback and contribution.
Yes, sure I can help you.
Could you please fork the project and push your modifications to a branch ? Then I could review the changes and errors.

**Comment by julienboulay** [comment]
@lucifer63 I pushed the latest master version. The component build correctly.
Could you try to pull the latest version, remove the `node_modules` and rerun `npm i`

**Comment by lucifer63** [comment]
Wow, thanks for such a quick response, i didn't expect this) Ok, i'll try to do it, it will take an hour maybe

**Comment by lucifer63** [comment]
Thanks again, everything works as expected. Can i also ask you to publish it to npm?

**Comment by julienboulay** [comment]
I'm sorry for the delay, but I just realized that I was no longer receiving github notifications after a change of email address.
The new version is now released : 0.0.6
