### ISSUE TITLE
Any plans on moving to quagga2 lib?

### ISSUE THREAD

**Issue by Naruto248** [julienboulay/ngx-barcode-scanner#51]
Hey, just wanted to know if there are any plans on moving to @ericblade/quagga2 library as the original Quagga lib is not maintained anymore and it has some optimization issues and also has issues with running on newer browsers/devices. 

It would be great if we could move to quagga2 as well. Thanks!

**Comment by julienboulay** [comment]
The new v0.2.0 now support [@ericblade/quagga2](https://github.com/serratus/quaggaJS) instead of [serratus/quaggaJS](https://github.com/serratus/quaggaJS)
