### ISSUE TITLE
Unexpected callable expression from (started)="(onStarted)"

### ISSUE THREAD

**Issue by HunteRoi** [julienboulay/ngx-barcode-scanner#56]
We often say an image is worth a hundred words. There we go!

![image](https://user-images.githubusercontent.com/32441291/106026508-2ed05e80-60ca-11eb-9a0e-a0fda5f84edd.png)

I copy-pasted the code from your example written in your README. What do you think about this warning?

**Comment by julienboulay** [comment]
Hi @HunteRoi,
I think that this code from the README is wrong.
It should be 
```html
<barcode-scanner-livestream
    type="ean"
    (valueChanges)="onBarcodeScanned($event)"
    (started)="onStarted()"
></barcode-scanner-livestream>
```

I will fix it soon

**Comment by HunteRoi** [comment]
You will not be able to compile then : 
![image](https://user-images.githubusercontent.com/32441291/106131231-b9649c80-6162-11eb-903b-c0a42c74d5e9.png)

**Comment by julienboulay** [comment]
yes, I forgot to pass the event value : `onStarted($event)`

**Comment by HunteRoi** [comment]
That's it :D
