### ISSUE TITLE
How to change default config?

### ISSUE THREAD

**Issue by yakirTsuberi** [julienboulay/ngx-barcode-scanner#6]
I want to change a few options in DEFAULT_CONFIG of quagga, how I can do it?

**Comment by julienboulay** [comment]
Hi @yakirTsuberi,
I need to implement some changes on the component to allow modifying the default config.
It is not possible in the current version.
I hope to find the time to do it soon.
You can submit a PR if you want.
Thanks

**Comment by julienboulay** [comment]
Please list the configuration parameters that should be available

**Comment by lucifer63** [comment]
Maybe inputStream.constraints.aspectRatio, in relation with https://github.com/julienboulay/ngx-barcode-scanner/issues/43
