### ISSUE TITLE
NotAllowedError: Permission denied

### ISSUE THREAD

**Issue by fkolar** [julienboulay/ngx-barcode-scanner#7]
I tried to test it and follow the steps but I am getting this error:

```
quagga.min.js:formatted:1 ERROR Error: Uncaught (in promise): NotAllowedError: Permission denied
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (quagga.min.js:formatted:1)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)

```

I am using it with regular Chrome Browser and USB Barcode reader

**Comment by julienboulay** [comment]
Hi @fkolar, 

Could you please give more details about how you integrated ngx-barcode-scanner with this USB Barcode reader ? 
Could you please try to use the standard quaggajs example before using this angular version
https://serratus.github.io/quaggaJS/examples/live_w_locator.html

**Comment by fkolar** [comment]
The barcode scanner I have is regular (https://www.sensodroid.com/p/automaticka-ctecka-carovych-kodu-sensodroid-t-760a?gclid=EAIaIQobChMI2_vm_I_P4AIVB4XVCh2E0geyEAQYAyABEgJDQfD_BwE) scanner that does not differ from any other. 

You plug it into USB port and you can start using right away if you just open some editor.  For the web app I just used simple INPUT field and if this field has a focus, it will receive set of characters  you scan with the device. 

The question would be shoudl this library work with such SCANNER? that act just like any other input device or this library is more targeted to the camera to take a picture and then do some post processing trying to identify hte code. ?

**Comment by julienboulay** [comment]
@fkolar 

> The question would be shoudl this library work with such SCANNER? that act just like any other input device or this library is more targeted to the camera to take a picture and then do some post processing trying to identify hte code. ?

This library is not supposed to work with such scanner. It is used to scan barcode with a camera (on your smartphone for example). You take a picture and the barcode is processed by quaggajs to interpret the code.
