### ISSUE TITLE
Torch-Support

### ISSUE THREAD

**Issue by ProfEibe** [julienboulay/ngx-barcode-scanner#76]
QuaggaJS has support to enable or disable the torch: https://serratus.github.io/quaggaJS/examples/live_w_locator.html

would be great if this could be added to this project as well.

**Comment by julienboulay** [comment]
hi @ProfEibe

Thank you for your feedback.
You're right, QuaggaJS support enabling/disabling the torch.
It could be nice to support it in ngx-barcode-scanner.
I currently don't have time to work on it , but will see to integrate it in the next release.
Feel free to suggest a pull request for it.

**Comment by ProfEibe** [comment]
My time is currently limited too, but I'll try to take a look at it.

**Comment by mer30boy** [comment]
hi

Is it possible to add this feature as soon as possible?

**Comment by benceHornyak** [comment]
hi 

I opened a PR for it :) let me know what you think. Happy to help out

**Comment by julienboulay** [comment]
Hi @benceHornyak,
Many thanks for your contribution.

I have tested on my iOS device, and the torch doesn't work.
It might be linked to this issue:
https://github.com/ericblade/quagga2/issues/397

Did you succeed to turn on the torch ? On which device / browser ?

**Comment by benceHornyak** [comment]
Yupp. Works with Nothing Phone (android) with brave browser

**Comment by julienboulay** [comment]
Hi @mer30boy,

The new 14.0.1 released yesterday got torch support thanks to @benceHornyak.
Please let me know if it solves your needs
