### ISSUE TITLE
ERROR Error: Uncaught (in promise): NotFoundError: Requested device not found

### ISSUE THREAD

**Issue by jnjaga24** [julienboulay/ngx-barcode-scanner#8]
i need to read bar codes from my angular web app. I simply followed the steps mentioned in [npm](https://www.npmjs.com/package/ngx-barcode-scanner).. But after implementing i am getting the below error.

core.js:1673 ERROR Error: Uncaught (in promise): NotFoundError: Requested device not found at resolvePromise (zone.js:831) at resolvePromise (zone.js:788) at zone.js:892 at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423) at Object.onInvokeTask (core.js:3811) at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422) at Zone../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195) at drainMicroTaskQueue (zone.js:601).

[stackoverflow](https://stackoverflow.com/q/56866853/7207508)  .

Please help...

**Comment by julienboulay** [comment]
Hi @jnjaga24,
It seems that your camera could not be found. Can you try the [quaggajs example](https://serratus.github.io/quaggaJS/examples/live_w_locator.html) to see if it can work with a vanilla JS version ?

**Comment by jnjaga24** [comment]
Hi @julienboulay  . Ya it working with vannilajs version.  Also it is working with ngx bar code scanner.
But the ngx bar code scanner is scanning the barcodes of "code_128" and one or two other types. is it possible to make the ngx bar code scanner to scan atleast 5-6 types of bar code?
` <barcode-scanner-livestream type="code_128" (valueChanges)="onValueChanges($event)"></barcode-scanner-livestream>

how can we modify the type to scan some other bar code types also?`
