### ISSUE TITLE
Unable to scan Code_128 type barcodes

### ISSUE THREAD

**Issue by hazaratt** [julienboulay/ngx-barcode-scanner#84]
![Bar123](https://user-images.githubusercontent.com/3618506/166860358-ecb43d50-c026-42cb-97e4-4cb7d2c25f67.PNG)

I tried to scan attached barcode but i am unable to read , Can someone help me on this.

Thanks Advance 

  sanityCheck(s) {
   
    return s.toUpperCase().match(/^(([0-9]{2})+?)*$/);
  }
  private _getMedian(arr: number[]): number {
    arr.sort((a, b) => a - b);
    const half = Math.floor(arr.length / 2);
    if (arr.length % 2 === 1) // Odd length
      return arr[half];
    return (arr[half - 1] + arr[half]) / 2.0;
  }
  isValid(result) {
    const errors: number[] = result.codeResult.decodedCodes
      .filter(_ => _.error !== undefined)
      .map(_ => _.error);

    const median = this._getMedian(errors);
   
    return median < 0.1; //!(median > 0.08 || errors.some(err => err > 0.1))
  }
  onValueChanges(result): void {
    if (this.sanityCheck(result.codeResult.code)) {

      if (this.isValid(result)) {
        this.barcodeValue = result.codeResult.code;
     
        this.validateAndAddBarCode();
      }
    }
  }

**Comment by julienboulay** [comment]
Hi @hazaratt,
Thank you for using this library.
Did you try to scan this code_128 barcode with standard Quaggajs ?
If not, can you try with [live example](https://serratus.github.io/quaggaJS/examples/live_w_locator.html) ?
If it doesn't work, it is not an issue with `ngx-barcode-scanner`, but it may be with quaggajs or you barcode image resolution.

**Comment by hazaratt** [comment]
> Hi @hazaratt, Thank you for using this library. Did you try to scan this code_128 barcode with standard Quaggajs ? If not, can you try with [live example](https://serratus.github.io/quaggaJS/examples/live_w_locator.html) ? If it doesn't work, it is not an issue with `ngx-barcode-scanner`, but it may be with quaggajs or you barcode image resolution.

@julienboulay Thanks for quick response

i tried Quaggajs also, but it is showing wrong values not reading correct value.

**Comment by julienboulay** [comment]
@hazaratt 
Sorry, I missed your answer.
I think that the resolution of your barcode is not good enough to be scanned with quaggajs.
I close this issue as it is not related to ngx-barcode-scanner wrapper, but more with quaggajs and image resolution.
