### ISSUE TITLE
Angular 8 update

### ISSUE THREAD

**Issue by anewtonlevey** [julienboulay/ngx-barcode-scanner#9]
This should probably be updated for Angular 8 at some point.

**Comment by pmora-DLG** [comment]
Is it giving you issues with angular 8?

**Comment by trueflywood** [comment]
I use this package in Angular 8 and I have no problem.

**Comment by norkator** [comment]
Angular 10 here and no problem

**Comment by arunpanchavadi** [comment]
It's not working with all types of barcodes. Works with code-128 when we tested.

**Comment by norkator** [comment]
> code-128

Some example originally had only code 128 but when I gave type as empty array it started to work with every one listed here: https://github.com/julienboulay/ngx-barcode-scanner/blob/master/projects/ngx-barcode-scanner/src/lib/barcode-scanner-livestream/barcode-types.ts

**Comment by julienboulay** [comment]
Upgraded to Angular 10 in v0.0.8
