### ISSUE TITLE
I need Upload pdf, image.. barcode reader 

### ISSUE THREAD

**Issue by Harinandhu** [julienboulay/ngx-barcode-scanner#98]
I need Upload pdf, image.. barcode reader plz help for it.

**Comment by julienboulay** [comment]
Hi @Harinandhu,

ngx-barcode-scanner only support livestream. 
It will not help you for upload and static barcode reading.
Check Quaggajs or Quagga2 to see how you can decode barcode from an static image or with a file input : 
- Static image : https://serratus.github.io/quaggaJS/examples/static_images.html
- File input : https://serratus.github.io/quaggaJS/examples/file_input.html
